# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_arm:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    
        # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: bullseye
          - arch: armv7
            distro: bullseye
          - arch: aarch64
            distro: buster
          - arch: armv7
            distro: buster
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          install: |
            apt-get update -y
            apt-get install -y git libsqlite3-dev libreadline6-dev libgpg-error-dev libgnutls28-dev libxslt-dev libssl-dev libmariadb-dev-compat unzip libtool automake libgcrypt20-dev wget build-essential gcc

          run: |
            cd $GITHUB_WORKSPACE
            cd ..
            wget https://github.com/Homegear/libhomegear-base/archive/master.zip
            unzip master.zip
            rm master.zip
            cd libhomegear-base-master
            ./makeRelease.sh
            cd $GITHUB_WORKSPACE
            ./makeRelease.sh
